name: Terraform Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create S3 Bucket if not exists
        run: |
          if ! aws s3api head-bucket --bucket calculadora-terraform-pracasecazaporizhzhya19981989 2>/dev/null; then
            echo "Creating new S3 bucket..."
            aws s3api create-bucket \
              --bucket calculadora-terraform-pracasecazaporizhzhya19981989 \
              --region ${{ secrets.AWS_REGION }} \
            
            aws s3api put-bucket-versioning \
              --bucket calculadora-terraform-pracasecazaporizhzhya19981989 \
              --versioning-configuration Status=Enabled
          else
            echo "S3 bucket already exists, continuing..."
          fi

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialize Terraform
        working-directory: terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan -out=tfplan

      - name: Apply Terraform
        working-directory: terraform
        run: terraform apply -auto-approve tfplan